# Data: LISS panel (Centerdata)

**The data is not in this repository, and it may not be added.** LISS data is free for scientific research, but everyone who uses it registers with the LISS Data Archive and signs a statement that they will not pass the data on to others. `data/liss/` is in `.gitignore` so that nothing from it can be committed by accident. To rerun the notebook, get your own copy as described below.

## What to download

From the [LISS Data Archive](https://www.dataarchive.lissdata.nl/), in **Stata format (.dta), English version**. Zipped or unzipped both work, and file names do not matter: the notebook unzips everything once and finds the `.dta` files itself.

| Folder | LISS study | Files |
|---|---|---|
| `data/liss/background/` | Background Variables | every monthly file, November 2007 to now (we used 220 files up to March 2026; November 2022 does not exist) |
| `data/liss/work_schooling/` | LISS Core Study: Work and Schooling | every wave (we used 18: `cw08a` to `cw25r`) |
| `data/liss/health/` | LISS Core Study: Health | every wave (we used 18: `ch07a` to `ch25r`) |

We also downloaded *Economic Situation: Income* but do not use it (see notebook step 2e).

## Variables used

The full list of variables in every file, with question texts and answer codes, is in [`docs/liss_overview.md`](../docs/liss_overview.md) (generated by [`scripts/liss_inventory.py`](../scripts/liss_inventory.py); it contains no data about respondents). In the core studies a variable is called `<wave prefix><question number>`, for example `cw08a121`; the question numbers and answer codes are the same in every wave.

| Source | Variable | Used as |
|---|---|---|
| Background Variables | `nomem_encr` | encrypted person number: linking files and splitting by person; never shown |
| | `wave` | month of the file |
| | `belbezig` | primary occupation: finds job losses (1-3 paid work → 4 job seeker following job loss) and the target |
| | `leeftijd`, `oplmet`, `aantalhh`, `aantalki`, `partner`, `woonvorm`, `sted`, `nettoink_f` | age, education, household size, children at home, partner, domestic situation, urbanity, net monthly income (imputed), all from the last month in work |
| | `geslacht` | gender, for fairness checks only, not a feature |
| | `herkomstgroep` | migration background, for fairness checks only, not a feature |
| Work and Schooling | question 121, 122, 126, 134, 402, 404, 409, 408 / 528 | contract type, public or private organisation, contract hours, year started with the employer, sector, occupation, supervises others, firm size (408 until 2010, 528 from 2011) |
| | `<prefix>_m` | interview month, to take the most recent interview *before* the job loss |
| Health | question 004, 018, 020 | self-rated health, long-standing disease, health hinders daily activities |
| | `<prefix>_m` | interview month |

## Licence and citation

Use is subject to the *statement on the use of LISS data* and the [LISS general terms and conditions](https://www.lissdata.nl/general-terms-and-conditions): use for scientific research, no passing on of the data, no publication of information about individual persons or households, and acknowledgement in every publication. Our acknowledgement:

> In this project use is made of data of the LISS (Longitudinal Internet studies for the Social Sciences) panel administered by Centerdata (Tilburg University, The Netherlands).
